# Generated by Django 5.1.5 on 2025-02-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=254, verbose_name='ユーザーID')),
                ('delivery_name', models.CharField(max_length=254, verbose_name='宛先名称')),
                ('email_address', models.CharField(max_length=254, verbose_name='メールアドレス')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'email_address'), name='unique_user_id_email_address')],
            },
        ),
    ]
