# Generated by Django 5.1.5 on 2025-02-08 09:04

import django.db.models.deletion
from django.db import migrations, models
from api.models import FuelOrderTargetJa

def add_initial_data(apps, schema_editor):
    farm_field_ids = ['farm-field-a','farm-field-b','farm-field-c']
    for farm_field_id in farm_field_ids:
        FuelOrderTargetJa.objects.create(user_id='hoge', farm_field_id=farm_field_id, ja_branch_office_id=1).save()

def remove_initial_data(apps, schema_editor):
    FuelOrderTargetJa.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jabranchoffice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelOrderTargetJa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=254, verbose_name='ユーザーID')),
                ('farm_field_id', models.CharField(max_length=254, verbose_name='圃場ID')),
                ('ja_branch_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jabranchoffice', verbose_name='店番号')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'farm_field_id'), name='unique_user_id_farm_field_id')],
            },
        ),
        migrations.RunPython(add_initial_data,remove_initial_data)
    ]
