# Generated by Django 5.1.5 on 2025-02-09 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fuelordertargetja'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=254, verbose_name='ユーザーID')),
                ('farm_field_id', models.CharField(max_length=254, verbose_name='圃場ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='発注日時')),
                ('fuel_type', models.CharField(max_length=10, verbose_name='燃料種類')),
                ('quantity', models.IntegerField(verbose_name='数量（L）')),
                ('status', models.CharField(max_length=10, verbose_name='ステータス')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='fuelordertargetja',
            name='unique_user_id_farm_field_id',
        ),
        migrations.AddField(
            model_name='fuelorder',
            name='ja_branch_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jabranchoffice', verbose_name='店番号'),
        ),
    ]
