# Generated by Django 5.1.5 on 2025-02-19 05:52

import uuid
from datetime import datetime, timezone, timedelta
from django.db import migrations, models

from api.models import WarningHistory

JST = timezone(timedelta(hours=+9), 'JST')

def add_initial_data(apps, schema_editor):
    warning_histories = [
        WarningHistory(
            user_id='hoge',
            farm_field_id='farm-field-a',
            warning_name='高温注意',
            warning_date_time= datetime(2024, 8, 10, 12, 15, tzinfo=JST),
        ),
        WarningHistory(
            user_id='hoge',
            farm_field_id='farm-field-b',
            warning_name='高温注意',
            warning_date_time= datetime(2024, 8, 10, 12, 10, tzinfo=JST),
        ),
        WarningHistory(
            user_id='hoge',
            farm_field_id='farm-field-a',
            warning_name='低温注意',
            warning_date_time= datetime(2024, 2, 1, 3, 20, tzinfo=JST),
        ),
        WarningHistory(
            user_id='hoge',
            farm_field_id='farm-field-c',
            warning_name='低温注意',
            warning_date_time= datetime(2024, 2, 1, 3, 25, tzinfo=JST),
        ),
    ]
    WarningHistory.objects.bulk_create(warning_histories)

def remove_initial_data(apps, schema_editor):
    WarningHistory.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fuelorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=254, verbose_name='ユーザーID')),
                ('farm_field_id', models.CharField(max_length=254, verbose_name='圃場ID')),
                ('warning_name', models.CharField(max_length=254, verbose_name='警報名称')),
                ('warning_date_time', models.DateTimeField(verbose_name='監視開始時刻')),
            ],
        ),
        migrations.CreateModel(
            name='WarningMailSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=254, verbose_name='ユーザーID')),
                ('farm_field_id', models.CharField(max_length=254, verbose_name='圃場ID')),
                ('warning_name', models.CharField(max_length=254, verbose_name='警報名称')),
                ('monitoring_start_time', models.TimeField(verbose_name='監視開始時刻')),
                ('monitoring_end_time', models.TimeField(verbose_name='監視終了時刻')),
                ('monitoring_sensor', models.CharField(max_length=254, verbose_name='監視センサー')),
                ('monitoring_condition', models.CharField(max_length=254, verbose_name='監視条件')),
                ('monitoring_value', models.FloatField(verbose_name='監視数値')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='継続時間（分）')),
                ('enabled', models.BooleanField(verbose_name='有効')),
            ],
        ),
        migrations.RunPython(add_initial_data, remove_initial_data),
    ]
